baseURL = "https://www.praveenjuge.xyz/"
languageCode = "en-us"
title = "Praveen Juge"

enableRobotsTXT = true
enableEmoji = true
canonifyURLs = true
enableGitInfo = true

pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "manni"

googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  description = "Praveen Juge is designing and making things for-and-in web, this is his personal website. And he likes speaking about himself in third person."
  ogimage = "images/praveen-juge.png"
  ISO8601 = "2006-01-02T15:04:05JST"

[author]
  name = "Praveen Juge"
  github = "praveenjuge"
  twitter = "praveenjuge"
  dribbble = "praveenjuge"
  instagram = "praveenjuge"
  email = "praveen@skcript.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xHTML = false
