baseURL = "https://praveenjuge.netlify.com"
languageCode = "en-us"
title = "Praveen Juge"

enableRobotsTXT = true
enableEmoji = true
canonifyURLs = true
enableGitInfo = true

pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "manni"

googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  description = "Praveen Juge is designing and making things for-and-in web, this is his personal website. And he likes speaking about himself in third person."
  ogimage = "images/praveen-juge.png"

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[author]
  name = "Praveen Juge"
  github = "praveenjuge"
  twitter = "praveenjuge"
  dribbble = "praveenjuge"
  email = "praveen@skcript.com"
